name: CI-iOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Select latest Xcode
        uses: devbotsxyz/xcode-select@v1.1.0
        with:
          version: latest
          beta: false
      
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'
          
      - run: flutter pub get
      - run: flutter pub global activate intl_utils
      - run: flutter pub global run intl_utils:generate
          
      - run: flutter pub global activate cider
      - name: Bump Build Number
        run: flutter pub run cider bump build
      
      - name: Get flutter version
        id: get_flutter_version
        uses: its404/get-flutter-version@v1.0.0
      
      - name: Update Xcode build number
        uses: yanamura/ios-bump-version@v1
        with:
          version: 1.1.0
          build-number: ${{ steps.get_flutter_version.outputs.build_number }}
          project-path: ios
      
      - name: Commit build number update
        run: |
          git add .
          git commit -m "[GitHub Action] Bump Build Number"
          git push origin HEAD
      
      - name: Import Codesign Certificates
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
  
      - name: Archive IPA
        run: flutter build ipa # --bundle-sksl-path sksl_default.json
        
      # - name: Export IPA
      #   run: xcodebuild -exportArchive -archivePath build/ios/archive/Runner.xcarchive -exportPath build/ios/archive/Runner.ipa -exportOptionsPlist build/ios/archive/RunnerOptions.plist
      
      - run: mkdir private_keys
      - run: echo -n ${{ secrets.APP_STORE_API_KEY_BASE64 }} | base64 -d -o ./private_keys/AuthKey_${{ secrets.APP_STORE_API_KEY_ID }}.p8
          
      - name: Upload app to TestFlight
        run: xcrun altool --upload-app -f build/ios/archive/Runner.xcarchive --type ios --apiKey ${{ secrets.APP_STORE_API_KEY_ID }} --apiIssuer ${{ secrets.APP_STORE_API_ISSUER_ID }}
