name: CI-iOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Select Latest Xcode
        uses: devbotsxyz/xcode-select@v1.1.0
        with:
          version: latest
          beta: false
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'
          
      - name: Prepare Flutter Dependencies
        run: |
          flutter pub get
          flutter pub global activate intl_utils
          flutter pub global run intl_utils:generate
          
      - name: Bump Build Number
        run: |
          flutter pub global activate cider
          flutter pub global run cider bump build
      
      - name: Get Flutter Version
        id: get_flutter_version
        uses: its404/get-flutter-version@v1.0.0
      
      - name: Update Xcode Build Number
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{ steps.get_flutter_version.outputs.version_number }}
          build-number: ${{ steps.get_flutter_version.outputs.build_number }}
          project-path: ios
      
      - name: Commit Build Number Update
        run: |
          git add .
          git commit -m "[GitHub Action] Bump Build Number"
          git push origin HEAD
          
      - name: Import Development Code Sign Certificates
        id: dev-codesign
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      
      - name: Import Distribution Code Sign Certificates
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.DISTRIBUTION_CERTIFICATE_P12 }}
          p12-password: ${{ secrets.DISTRIBUTION_CERTIFICATE_P12_PASSWORD }}
          keychain-password: ${{ steps.dev-codesign.outputs.keychain-password }}
          create-keychain: false
          
      - name: Import API Keys
        run: |
          mkdir private_keys
          echo -e "${{ secrets.APP_STORE_API_KEY }}" > ./private_keys/AuthKey_${{ secrets.APP_STORE_API_KEY_ID }}.p8

      - name: Import Secret.dart
        run: echo -n ${{ secrets.SECRET_DART_BASE64 }} | base64 -d > lib/common/Secret.dart

      - name: Configure Xcode
        run: flutter build ios --release --config-only # --bundle-sksl-path sksl_default.json # leave this to integration tests

      - name: Build App - Pass 1 (account configuration)  # [flutter pub run build_runner build] will automatically run in this step
        run: xcodebuild archive -archivePath build/ios/archive/Runner.xcarchive -workspace ios/Runner.xcworkspace -scheme Runner -quiet -allowProvisioningUpdates -authenticationKeyPath $(pwd)/private_keys/AuthKey_${{ secrets.APP_STORE_API_KEY_ID }}.p8 -authenticationKeyID ${{ secrets.APP_STORE_API_KEY_ID }} -authenticationKeyIssuerID ${{ secrets.APP_STORE_API_ISSUER_ID }}
        
      - name: Build App - Pass 2 (real build)
        run: flutter build ios --release # --bundle-sksl-path sksl_default.json # leave this to integration tests
        
      #- name: Export Archive
      #  run: xcodebuild -exportArchive -archivePath build/ios/archive/Runner.xcarchive -exportPath build/ios/archive/Runner.ipa -exportOptionsPlist CI/ExportOptions.plist -allowProvisioningUpdates -authenticationKeyPath $(pwd)/private_keys/AuthKey_${{ secrets.APP_STORE_API_KEY_ID }}.p8 -authenticationKeyID ${{ secrets.APP_STORE_API_KEY_ID }} -authenticationKeyIssuerID ${{ secrets.APP_STORE_API_ISSUER_ID }}

      - name: Upload app to App Store Connect
        run: xcrun altool --upload-package build/ios/iphoneos/Runner.ipa --type ios --asc-public-id ${{ secrets.APP_STORE_API_ISSUER_ID }} --apple-id 1568629997 --bundle-version ${{ steps.get_flutter_version.outputs.build_number }} --bundle-short-version-string ${{ steps.get_flutter_version.outputs.version_number }} --bundle-id io.github.danxi-dev.dan-xi --apiKey ${{ secrets.APP_STORE_API_KEY_ID }} --apiIssuer ${{ secrets.APP_STORE_API_ISSUER_ID }}
