name: Dart

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.0'
        channel: 'stable'
    - run: flutter pub get
      #Testing is still useless at the moment.
      #- run: flutter test
    - run: ./build_ios pre
      # Use debug profile to sign with no specific keystore
    - run: flutter build apk --debug


