name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.1"
          channel: "stable"

      - name: Prepare Dependencies
        run: |
          flutter pub get
          flutter pub global activate intl_utils
          flutter pub global run intl_utils:generate

      - name: Generate Models
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Import Keys
        run: |
          echo -n "${{ secrets.MATCH_SSH_KEY_BASE64 }}" | base64 -d -o $HOME/.ssh/id_rsa
          chmod 400 $HOME/.ssh/id_rsa

      - name: Configure Git
        run: |
          git config --global user.email "1296845690@qq.com"
          git config --global user.name "KYLN24"

      - name: Build & Upload
        run: |
          flutter build web --release
          cd build/web
          git init -b gh-pages
          git add -A
          git commit -m 'gh-action deploy'
          git push -f "git@github.com:DanXi-Dev/DanXi" gh-pages
